### ISSUE TITLE
Caught exception evaluating: `!it.builds.isEmpty()` in `/jenkins/safeRestart`

### ISSUE THREAD

**Issue by felipecrs** [jenkinsci/next-executions-plugin#147]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.462.3
  OS: Linux - 5.15.0-122-generic
  Java: 11.0.24 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
  ---
  Parameterized-Remote-Trigger:3.2.0
  allure-jenkins-plugin:2.31.1
  ansicolor:1.0.5
  antisamy-markup-formatter:162.v0e6ec0fcfcf6
  apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
  asm-api:9.7.1-97.v4cc844130d97
  authentication-tokens:1.119.v50285141b_7e1
  authorize-project:1.8.0
  basic-branch-build-strategies:81.v05e333931c7d
  blueocean:1.27.16
  blueocean-bitbucket-pipeline:1.27.16
  blueocean-commons:1.27.16
  blueocean-config:1.27.16
  blueocean-core-js:1.27.16
  blueocean-dashboard:1.27.16
  blueocean-display-url:2.4.3
  blueocean-events:1.27.16
  blueocean-git-pipeline:1.27.16
  blueocean-github-pipeline:1.27.16
  blueocean-i18n:1.27.16
  blueocean-jwt:1.27.16
  blueocean-personalization:1.27.16
  blueocean-pipeline-api-impl:1.27.16
  blueocean-pipeline-editor:1.27.16
  blueocean-pipeline-scm-api:1.27.16
  blueocean-rest:1.27.16
  blueocean-rest-impl:1.27.16
  blueocean-web:1.27.16
  bootstrap5-api:5.3.3-1
  bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
  branch-api:2.1178.v969d9eb_c728e
  build-name-setter:2.4.3
  build-timeout:1.33
  caffeine-api:3.1.8-133.v17b_1ff2e0599
  checks-api:2.2.1
  cloudbees-bitbucket-branch-source:888.v8e6d479a_1730
  cloudbees-folder:6.955.v81e2a_35c08d3
  cloudbees-jenkins-advisor:358.v58972d19b_1f0
  command-launcher:115.vd8b_301cc15d0
  commons-compress-api:1.26.1-2
  commons-lang3-api:3.17.0-84.vb_b_938040b_078
  commons-text-api:1.12.0-129.v99a_50df237f7
  configuration-as-code:1850.va_a_8c31d3158b_
  copyartifact:749.vfb_dca_a_9b_6549
  credentials:1384.vf0a_2ed06f9c6
  credentials-binding:681.vf91669a_32e45
  cucumber-reports:5.8.3
  dark-theme:479.v661b_1b_911c01
  data-tables-api:2.1.8-1
  display-url-api:2.204.vf6fddd8a_8b_e9
  docker-commons:443.v921729d5611d
  docker-workflow:580.vc0c340686b_54
  durable-task:577.v2a_8a_4b_7c0247
  echarts-api:5.5.1-3
  eddsa-api:0.3.0-4.v84c6f0f4969e
  email-ext:1844.v3ea_a_b_842374a_
  embeddable-build-status:487.va_0ef04c898a_2
  extended-read-permission:53.v6499940139e5
  favorite:2.221.v19ca_666b_62f5
  file-parameters:339.v4b_cc83e11455
  font-awesome-api:6.6.0-2
  generic-webhook-trigger:2.2.5
  gerrit-code-review:0.4.9
  gerrit-trigger:2.41.1
  git:5.5.2
  git-client:5.0.0
  github:1.40.0
  github-api:1.321-468.v6a_9f5f2d5a_7e
  github-branch-source:1803.v98e3d8a_c8169
  gitlab-api:5.6.0-97.v6603a_83f8690
  gitlab-branch-source:711.v41fb_c8b_2b_7a_e
  gson-api:2.11.0-85.v1f4e87273c33
  handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
  htmlpublisher:1.36
  instance-identity:201.vd2a_b_5a_468a_a_6
  ionicons-api:74.v93d5eb_813d5f
  jackson2-api:2.17.0-379.v02de8ec9f64c
  jacoco:3.3.6
  jakarta-activation-api:2.1.3-1
  jakarta-mail-api:2.1.3-1
  javadoc:280.v050b_5c849f69
  javax-activation-api:1.2.0-7
  javax-mail-api:1.6.2-10
  jaxb:2.3.9-1
  jdk-tool:80.v8a_dee33ed6f0
  jenkins-design-language:1.27.16
  jersey2-api:2.44-151.v6df377fff741
  jjwt-api:0.11.5-112.ve82dfb_224b_a_d
  job-dsl:1.89
  joda-time-api:2.13.0-93.v9934da_29b_a_e9
  jquery3-api:3.7.1-2
  jsch:0.2.16-86.v42e010d9484b_
  json-api:20240303-101.v7a_8666713110
  json-path-api:2.9.0-118.v7f23ed82a_8b_8
  junit:1307.vdd5b_2646279e
  kubernetes:4295.v7fa_01b_309c95
  kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
  kubernetes-credentials:190.v03c305394deb_
  ldap:725.v3cb_b_711b_1a_ef
  lockable-resources:1320.v1f0dff578476
  mailer:488.v0c9639c1a_eb_3
  mapdb-api:1.0.9-40.v58107308b_7a_7
  matrix-auth:3.2.2
  matrix-project:839.vff91cd7e3a_b_2
  metrics:4.2.21-451.vd51df8df52ec
  mina-sshd-api-common:2.14.0-133.vcc091215a_358
  mina-sshd-api-core:2.14.0-133.vcc091215a_358
  next-executions:392.v1d10c1b_5926f
  okhttp-api:4.11.0-172.vda_da_1feeb_c6e
  pam-auth:1.11
  pipeline-build-step:540.vb_e8849e1a_b_d8
  pipeline-github-lib:61.v629f2cc41d83
  pipeline-graph-analysis:216.vfd8b_ece330ca_
  pipeline-graph-view:340.v28cecee8b_25f
  pipeline-groovy-lib:740.va_2701257fe8d
  pipeline-input-step:495.ve9c153f6067b_
  pipeline-milestone-step:119.vdfdc43fc3b_9a_
  pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
  pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
  pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
  pipeline-rest-api:2.34
  pipeline-stage-step:312.v8cd10304c27a_
  pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
  pipeline-stage-view:2.34
  pipeline-utility-steps:2.18.0
  plain-credentials:183.va_de8f1dd5a_2b_
  plugin-util-api:5.1.0
  prism-api:1.29.0-17
  pubsub-light:1.18
  purge-build-queue-plugin:88.v23b_97b_f2c7a_d
  rebuild:332.va_1ee476d8f6d
  resource-disposer:0.24
  role-strategy:743.v142ea_b_d5f1d3
  saferestart:0.7
  scm-api:696.v778d637b_a_762
  script-security:1365.v4778ca_84b_de5
  snakeyaml-api:2.3-123.v13484c65210a_
  sonar:2.17.2
  sonar-gerrit:388.v9b_f1cb_e42306
  sse-gateway:1.27
  ssh-credentials:343.v884f71d78167
  sshd:3.330.vc866a_8389b_58
  structs:338.v848422169819
  support-core:1511.v3f5cc9b_a_ff55
  theme-manager:262.vc57ee4a_eda_5d
  timestamper:1.27
  token-macro:400.v35420b_922dcb_
  trilead-api:2.147.vb_73cc728a_32e
  uno-choice:2.8.4
  variant:60.v7290fc0eb_b_cd
  workflow-aggregator:600.vb_57cdd26fdd7
  workflow-api:1336.vee415d95c521
  workflow-basic-steps:1058.vcb_fc1e3a_21a_9
  workflow-cps:3975.v567e2a_1ffa_22
  workflow-durable-task-step:1371.vb_7cec8f3b_95e
  workflow-job:1436.vfa_244484591f
  workflow-multibranch:795.ve0cb_1f45ca_9a_
  workflow-scm-step:427.v4ca_6512e7df1
  workflow-step-api:678.v3ee58b_469476
  workflow-support:930.vf51d22b_ce488
  ws-cleanup:0.47
  
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 22.04, docker.

### Reproduction steps

Attempt to _Restart Safely_, and the following log is generated in the controller:

<details>
  <summary>Click here to show the logs</summary>

```
2024-10-18 15:31:48.340+0000 [id=355404]	WARNING	h.ExpressionFactory2$JexlExpression#evaluate: Caught exception evaluating: !it.builds.isEmpty() in /jenkins/safeRestart. Reason: java.lang.reflect.InvocationTargetException
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTrigger
	at PluginClassLoader for next-executions//hudson.plugins.nextexecutions.utils.ParameterizedNextExecutionsUtils.getNextBuild(ParameterizedNextExecutionsUtils.java:52)
	at PluginClassLoader for next-executions//hudson.plugins.nextexecutions.NextExecutionsWidget.getBuilds(NextExecutionsWidget.java:100)
Caused: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor2793.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.commons.jexl.util.PropertyExecutor.execute(PropertyExecutor.java:125)
	at org.apache.commons.jexl.util.introspection.UberspectImpl$VelGetterImpl.invoke(UberspectImpl.java:314)
	at org.apache.commons.jexl.parser.ASTArrayAccess.evaluateExpr(ASTArrayAccess.java:185)
	at org.apache.commons.jexl.parser.ASTIdentifier.execute(ASTIdentifier.java:75)
	at org.apache.commons.jexl.parser.ASTReference.execute(ASTReference.java:83)
	at org.apache.commons.jexl.parser.ASTReference.value(ASTReference.java:57)
	at org.apache.commons.jexl.parser.ASTNotNode.value(ASTNotNode.java:56)
	at org.apache.commons.jexl.parser.ASTExpression.value(ASTExpression.java:54)
	at org.apache.commons.jexl.parser.ASTExpressionExpression.value(ASTExpressionExpression.java:56)
	at org.apache.commons.jexl.ExpressionImpl.evaluate(ExpressionImpl.java:80)
	at hudson.ExpressionFactory2$JexlExpression.evaluate(ExpressionFactory2.java:76)
	at org.apache.commons.jelly.expression.ExpressionSupport.evaluateRecurse(ExpressionSupport.java:61)
	at org.apache.commons.jelly.expression.ExpressionSupport.evaluateAsBoolean(ExpressionSupport.java:71)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$1.run(CoreTagLibrary.java:97)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:100)
	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:102)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.OtherwiseTag.doTag(OtherwiseTag.java:41)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:102)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.ChooseTag.doTag(ChooseTag.java:38)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:102)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:121)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$1.run(CoreTagLibrary.java:98)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:98)
	at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:175)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
	at org.apache.commons.jelly.tags.core.ForEachTag.doTag(ForEachTag.java:150)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:100)
	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:102)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$1.run(CoreTagLibrary.java:98)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:121)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:98)
	at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:175)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:98)
	at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:175)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:100)
	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$1.run(CoreTagLibrary.java:98)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:102)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:102)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:102)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:100)
	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:271)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:121)
	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:121)
	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:98)
	at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:67)
	at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:55)
	at org.kohsuke.stapler.jelly.ScriptInvoker.execute(ScriptInvoker.java:59)
	at org.kohsuke.stapler.jelly.ScriptInvoker.execute(ScriptInvoker.java:42)
	at org.kohsuke.stapler.ScriptRequestDispatcher.forward(ScriptRequestDispatcher.java:103)
	at org.kohsuke.stapler.ForwardToView.generateResponse(ForwardToView.java:108)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.handleHttpResponse(HttpResponseRenderer.java:130)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.generateResponse(HttpResponseRenderer.java:71)
	at org.kohsuke.stapler.Function.renderResponse(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:644)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:61)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:827)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:253)
	at Jenkins Main ClassLoader//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:163)
	at PluginClassLoader for sse-gateway//org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:248)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
	at PluginClassLoader for blueocean-web//io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
	at PluginClassLoader for blueocean-jwt//io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:60)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
	at PluginClassLoader for metrics//jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
	at jenkins.util.HttpServletFilter$1.doFilter(HttpServletFilter.java:76)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:166)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at jenkins.ErrorAttributeFilter.doFilter(ErrorAttributeFilter.java:29)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:160)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:110)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:31)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at Jenkins Main ClassLoader//org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.Server.handle(Server.java:563)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-10-18 15:31:48.358+0000 [id=355404]	WARNING	h.ExpressionFactory2$JexlExpression#evaluate: Caught exception evaluating: it.builds.isEmpty() in /jenkins/safeRestart. Reason: java.lang.reflect.InvocationTargetException
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTrigger
	at PluginClassLoader for next-executions//hudson.plugins.nextexecutions.utils.ParameterizedNextExecutionsUtils.getNextBuild(ParameterizedNextExecutionsUtils.java:52)
	at PluginClassLoader for next-executions//hudson.plugins.nextexecutions.NextExecutionsWidget.getBuilds(NextExecutionsWidget.java:100)
Caused: java.lang.reflect.InvocationTargetException
```

</details>

And given this part:

```
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTrigger
	at PluginClassLoader for next-executions//hudson.plugins.nextexecutions.utils.ParameterizedNextExecutionsUtils.getNextBuild(ParameterizedNextExecutionsUtils.java:52)
	at PluginClassLoader for next-executions//hudson.plugins.nextexecutions.NextExecutionsWidget.getBuilds(NextExecutionsWidget.java:100)
```

I assume this issue could be somehow related to this plugin.

### Expected Results

To not issue any errors.

### Actual Results

Check above.

**Comment by jonesbusy** [comment]
You are missing https://plugins.jenkins.io/parameterized-scheduler/ if displaying the widget for parameterized execution 

https://github.com/jenkinsci/next-executions-plugin?tab=readme-ov-file#parameterized-scheduler-plugin

**Comment by felipecrs** [comment]
Oh ok, that would make sense. Thank you very much.
